# Generated by Django 4.0 on 2022-04-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=1000)),
                ('asset_desc', models.TextField()),
                ('asset_cor1', models.FloatField()),
                ('asset_cor2', models.FloatField()),
                ('asset_date_time', models.DateTimeField()),
            ],
        ),
    ]
