# Generated by Django 4.0 on 2022-05-04 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_cor1',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_cor2',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_date_time',
        ),
        migrations.CreateModel(
            name='Asset_Cord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_cor1', models.FloatField()),
                ('asset_cor2', models.FloatField()),
                ('asset_date_time', models.DateTimeField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gps.asset')),
            ],
        ),
    ]
