# Generated by Django 4.0 on 2022-05-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0002_remove_asset_asset_cor1_remove_asset_asset_cor2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
